embed_assets: datauri
javascript_compressor: closure
template_function: _.template
gzip_assets: <% if $VS_MIN %>on<% else %>off<% end %>
compress_assets: <% if $VS_MIN %>on<% else %>off<% end %>

javascripts:
  dependencies:
    - vendor/jquery-*.js
    - vendor/jquery.ui.core.js
    - vendor/jquery.ui.widget.js
    - vendor/jquery.ui.position.js
    - vendor/jquery.ui.*.js
    - vendor/underscore-*.js
    - vendor/backbone-*.js
  visualsearch<% if $VS_MIN %>-min<% end %>:
    - public/js/visual_search.js
    - public/js/views/*.js
    - public/js/utils/*.js
    - public/js/models/*.js
    - public/js/templates/*.jst
  visualsearch_templates:
    - public/js/templates/*.jst

stylesheets:
  visualsearch:
    - public/css/*.css